"""add next_retry_at in delivery

Revision ID: 2ea825b91c0a
Revises: 303974e46da3
Create Date: 2026-06-11 11:53:56.971305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea825b91c0a'
down_revision: Union[str, Sequence[str], None] = '303974e46da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'next_retry_at')
    # ### end Alembic commands ###
