"""add api_key in tenant table

Revision ID: 620d4829eb8c
Revises: b0f998fc5e08
Create Date: 2026-04-28 17:46:32.268877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620d4829eb8c'
down_revision: Union[str, Sequence[str], None] = 'b0f998fc5e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('api_key', sa.String(length=64), nullable=False))
    op.add_column('tenant', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uq_tenant_api_key', 'tenant', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_api_key', 'tenant', type_='unique')
    op.drop_column('tenant', 'created_at')
    op.drop_column('tenant', 'api_key')
    # ### end Alembic commands ###
