"""add signing_secret in tenant table

Revision ID: 904574ba2e5b
Revises: 620d4829eb8c
Create Date: 2026-04-29 08:24:48.548483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904574ba2e5b'
down_revision: Union[str, Sequence[str], None] = '620d4829eb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('signing_secret', sa.String(length=64), nullable=False))
    op.create_unique_constraint(
        'uq_tenant_signing_secret', 'tenant', ['signing_secret']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_signing_secret', 'tenant', type_='unique')
    op.drop_column('tenant', 'signing_secret')
    # ### end Alembic commands ###
